<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>DisableShamanRunesAndroid</AssemblyName>
    <RootNamespace>DisableShamanRunesAndroid</RootNamespace>
    <Version>1.7.0</Version>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
    <RestoreSources></RestoreSources>
    <RestoreAdditionalProjectSources></RestoreAdditionalProjectSources>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>libs/BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>libs/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>libs/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>libs/UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
